baseURL = 'https://fredderf204.github.io/mmsa-website/'
copyright = "2023" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-US'
defaultContentLanguage = 'en'
theme = 'lowkey'
title = 'Migrate and Modernise Scale Accelerator'
enableRobotsTXT = true
summaryLength = 15
paginate = 5
toggle-theme = true
googleAnalytics = "G-7T7BLYN0RW"
favicon = "/mmsa-website/favicon.ico"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4