[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "overview"
    name = "Overview"
    url = "/posts/welcome/"
    weight = 2

[[main]]
    identifier = "events"
    name = "Events"
    url = "/posts/events/"
    weight = 3
    
# Social Media Configuration

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/fredderf204/mmsa-website"
    weight = 3